spring:
  # h2 임시 활성화
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/testDB  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  # 업로드 파일 용령 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

#  # MySQL 설정
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver
#    url: ${DB_URL}
#    username: ${DB_USERNAME} # RDS 사용자 이름
#    password: ${DB_PASSWORD} # RDS 사용자 비밀번호

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

#  # JPA 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
#    properties:
#      hibernate:
#        format_sql: true      # 쿼리 로그 포맷 (정렬)
#        show_sql: true        # 쿼리 로그 출력
#        jdbc:
#          batch_size: 100      # 배치 사이즈 설정
#    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  config:
    import:
      - s3bucket.yml

  portone:
    imp_key : ${secret.impKey}
    imp_secret: ${secret.impSecret}
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}

default:
  image:
    url: https://mosoobucket.s3.ap-northeast-2.amazonaws.com/test/752d474e-8c1d-45a8-bd77-b426f61e204e-d283f188e2c88f02.png

secret:
  impKey: ${impKey}
  impSecret: ${impSecret}